name: MLOps Pipeline

on:
  push:
    branches:
      - demo
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "REPO_OWNER=${{ secrets.REPO_OWNER }}" >> $GITHUB_ENV
        echo "REPO_NAME=${{ secrets.REPO_NAME }}" >> $GITHUB_ENV
        echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Run pipeline
      run: |
        python run_pipeline.py
